name: Random Github Action Experiments

on:
  push:
    branches:
      - test-random-github-action-experiments
      # - test-random-github-action-experiments-disabled-for-now

jobs:


  install-mitmproxy:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install mitmproxy
        run: |
          brew install mitmproxy
          mitmproxy --version

      - name: Start mitmproxy via mitmdump and kill it
        run: |
          set +e
          mitmdump & sleep 5;

          ./scripts/kill-mitmdump.sh
          sleep 3;

      - name: install certificate
        id: "install_certificate"
        run: |
          sudo security add-trusted-cert -d -p ssl -p basic -k /Library/Keychains/System.keychain ~/.mitmproxy/mitmproxy-ca-cert.pem

      #     # xcrun simctl list devices "iPhone 14"

      #     xcrun simctl boot "iPhone 14"

      #     # xcrun simctl getenv booted SIMULATOR_UDID

      #     # must boot first before adding root cert, add 5 mins to the process
      #     xcrun simctl keychain $(xcrun simctl getenv booted SIMULATOR_UDID) add-root-cert ~/.mitmproxy/mitmproxy-ca-cert.pem


      - name: networksetup list all
        run: |
          networksetup -listallnetworkservices
      # response:
      # Ethernet

      - name: test curl 1
        run: |
          curl -o /dev/null -s -w 'Total: %{time_total}s\n'  https://mobile-e2e-site-1.test.mattermost.cloud/api/v4/system/ping?get_server_status=true

      - name: throttle bandwidth down
        run: |
          echo "dummynet in from mobile-e2e-site-1.test.mattermost.cloud to any pipe 1
          dummynet out from any to mobile-e2e-site-1.test.mattermost.cloud pipe 2" | sudo pfctl -f -
          
          # pipe 1 is download, below is 3.3Mb/s with 1000ms latency
          sudo dnctl pipe 1 config bw 3300Kbit/s delay 1000ms
          
          # pipe 2 is upload, below is 3.3Mb/s with 1000ms latency
          sudo dnctl pipe 2 config bw 3300Kbit/s delay 1000ms
          
          sudo pfctl -E


      - name: start mitmdump
        run: |
          networksetup -setwebproxy Ethernet "127.0.0.1" "8080"
          networksetup -setsecurewebproxy Ethernet "127.0.0.1" "8080"

          mitmdump --allow-hosts 'community.mattermost.com' --ignore-hosts 'localhost' -s /Users/runner/work/mattermost-mobile/mattermost-mobile/scripts/mitmdump-flow-parsing.py &


      - name: test curl 2
        run: |
          curl -o /dev/null -s -w 'Total: %{time_total}s\n'  https://mobile-e2e-site-1.test.mattermost.cloud/api/v4/system/ping?get_server_status=true

      - name: test
        run: |
          curl --proxy 127.0.0.1:8080 --ca-cert ~/.mitmproxy/mitmproxy-ca-cert.pem https://mobile-e2e-site-1.test.mattermost.cloud/api/v4/system/ping?get_server_status=true
          curl --proxy 127.0.0.1:8080 https://mobile-e2e-site-1.test.mattermost.cloud/api/v4/system/ping?get_server_status=true


      - name: reset network settings
        run: |
          networksetup -setwebproxystate Ethernet "off"
          networksetup -setsecurewebproxystate Ethernet "off"

          sudo pfctl -d

          
      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifacts-${{ github.run_id }}
          path: /Users/runner/work/mattermost-mobile/mattermost-mobile/flow-output.csv
