name: Random Github Action Experiments

on:
  push:
    branches:
      - test-random-github-action-experiments

jobs:


  install-mitmproxy:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install mitmproxy
        run: |
          brew install mitmproxy
          mitmproxy --version

      - name: Start mitmproxy via mitmdump
        run: |
          mitmproxy
          sleep 5
          pkill -9 "mitmproxy"

      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifacts-${{ github.run_id }}
          path: ./.mitmproxy/


